
GEMINI_API_KEY="AIzaSyBCPmyQfNCHlHPK5gsgYn381c3fiRGlu0s"


QDRANT_URL="https://e701675d-7960-49f8-8771-c3e10159db66.europe-west3-0.gcp.cloud.qdrant.io"

QDRANT_API_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.pUV95XkXvPdwmMfFJ3PNnOIN6epzUe_YirYUVK5RhGs"

QDRANT_COLLECTION=book_vectors




